name: pure_dart_quic
description: A pure Dart implementation of.3, HTTP/3, and WebTransport, including packet protection, handshake key derivation, QPACK, and WebTransport DATAGRAM support
version: 1.0.1
repository: https://github.com/KellyKinyama/pure-dart-quic

environment:
  sdk: ^3.11.5

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.8.2
  collection: ^1.19.1
  crypto: ^3.0.7
  ecdsa: ^0.1.2
  elliptic: ^0.3.12
  events_emitter: ^0.5.2
  hex: ^0.2.0
  path: ^1.9.0
  pointycastle: ^4.0.0
  x25519: ^0.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
